### PR TITLE
test PR

### PR DESCRIPTION
**Pull request by dflazaro**
query fn

### CODE REVIEW

**Comment by mrutid** [comment]
¿merge to develop from master?... thats odd dude.

**Comment by mrutid** [comment]
Add me as a colaborator please.

**Comment by dflazaro** [comment]
I know is the other way arround. I did it from pycharm and this is what happened. My fault

**Comment by mrutid** [comment]
:) no problem, just notice it next time and try to fix it before send the PR.

Merged.

**Pull request merged**
